### ISSUE TITLE
Support CLI options to enable Puppet 4+ syntax

### ISSUE THREAD

**Issue by themasterchef** [neillturner/kitchen-puppet#90] opened 2015-10-16 17:04 UTC
One can pass '--parser future' to puppet apply to enable support for Puppet 4+ syntax, which is essential for the new looping constructs. However, because rebuilding the full puppet apply command is annoying, it would be nice if we could specify this argument separately.

On a related note, Puppet Labs decided to move a bunch of things around in Puppet 4, like packaging and executable locations - any indication on when kitchen-puppet will be upgraded to support the changes?

**Comment by looztra** [comment] 2015-10-17 07:21
I think this is a dupe of #87, I'm currently working on it

**Comment by neillturner** [comment] 2015-10-17 08:26
Well these is support for puppet v4 use the parameter
   require_puppet_collections: true
I've found that most of the puppet forge is incompatible with puppet v4 so hard to test. 
but there is basic support for puppet v4

**Comment by neillturner** [comment] 2015-11-12 11:48
Custom options #95 adds the ability  to have custom options so specifying in .kitchen.yml 
   custom_options: '--parser future'
will allow this

**Closed by neillturner** 2015-11-12 11:48 UTC
Labels: enhancement
